Merge YP core logic
YetiTool/easycut-smartbench pull request #1092
Opened 2023-03-10 15:29 UTC by archiepeterjarvis

2023-03-10 17:40 UTC, archiepeterjarvis commented on src/asmcnc/job/yetipilot/config/algorithm_parameters.json
> +      "Description": "Adjustment algorithm parameter"
These are specced by Ed & Benji

2023-03-10 17:43 UTC, archiepeterjarvis commented on src/asmcnc/job/yetipilot/yetipilot.py
> +        if self.sm.has_screen('go'):
it works atm

2023-03-10 17:43 UTC, archiepeterjarvis commented on src/asmcnc/job/yetipilot/yetipilot.py
> +        if len(self.digital_spindle_load_stack) == self.spindle_load_stack_size:
impossible

2023-03-10 17:53 UTC, LettyYeti requested changes

2023-03-10 17:53 UTC, LettyYeti commented on src/asmcnc/job/yetipilot/yetipilot.py
> +                    Clock.schedule_once(lambda dt: self.check_if_feed_too_low(), 4)
This unchecked clock has potential to throw up a screen at a semi-random time, i.e. if a user has already stopped or paused the job or the spindle has overloaded, then the job & YP could have been disabled but this screen can still be thrown up. Needs some kind of checks that only throw the error if the machine/console is in the right state.

2023-03-10 18:07 UTC, LettyYeti requested changes
Final test before merge

2023-03-12 14:43 UTC, LettyYeti commented on src/asmcnc/skavaUI/widget_speed_override.py
> +                try:
needs to happen normally as well

2023-03-12 18:10 UTC, LettyYeti approved these changes

2023-03-12 18:20 UTC, merged