Get spindle data
YetiTool/easycut-smartbench pull request #1194
Opened 2023-06-05 20:32 UTC by DennisKiselev

Show get spindle data button when SC2 is in use, which can be used to show a popup with spindle info on it (not localised)

Tested on rig, both connected and disconnected spindle

![image](https://github.com/YetiTool/easycut-smartbench/assets/75572055/99738764-ada6-42d6-88b7-c4cc157e0e4d)
![image](https://github.com/YetiTool/easycut-smartbench/assets/75572055/0b30cf15-37e7-4335-83b8-979e87ed8bd3)
![image](https://github.com/YetiTool/easycut-smartbench/assets/75572055/0fa0d7fc-ef91-475f-8aca-ec56837b4e41)

2023-06-06 18:36 UTC, DennisKiselev commented
![image](https://github.com/YetiTool/easycut-smartbench/assets/75572055/293f9c12-74a1-4524-9fec-ccf2b56bf056)

2023-06-12 10:49 UTC, LettyYeti commented
Recommend merging master back into both branches to make sure that the flat spindle image updates aren't overwritten by graphical changes in the this PR

2023-06-12 11:05 UTC, LettyYeti requested changes

2023-06-12 11:05 UTC, LettyYeti commented on src/asmcnc/apps/maintenance_app/widget_maintenance_spindle_settings.py
> +        if self.m.state().startswith('Idle'):
probably safer to use if not self.m.smartbench_is_busy() instead - it's a bit more thorough

2023-06-12 11:07 UTC, LettyYeti commented
In the SC2 spindle data popup, hardly any info is reported. Does your spindle not have any info programmed into it?

2023-06-12 13:13 UTC, DennisKiselev commented
> Recommend merging master back into both branches to make sure that the flat spindle image updates aren't overwritten by graphical changes in the this PR

Flat spindle images PR is off of this branch, so I will merge that one first before this one and there should be no conflicts

2023-06-12 13:15 UTC, DennisKiselev commented
> In the SC2 spindle data popup, hardly any info is reported. Does your spindle not have any info programmed into it?

It's a screenshot from windows, so there won't be any real data, it definitely works correctly on the rig 🙂

2023-06-12 13:28 UTC, DennisKiselev commented
![image](https://github.com/YetiTool/easycut-smartbench/assets/75572055/99634f48-5f97-4470-8b6c-912bb2eb288b)

2023-06-12 19:07 UTC, merged