Incorrect shutdown screen
YetiTool/easycut-smartbench pull request #1253
Opened 2023-09-27 13:57 UTC by VladPavelescu

Tested on the rig and on big console. A "correct_shutdown" flag gets set to False if it doesn't already exist or if it is currently set to True on startup. The flag is set to True only when the user shuts down the console from the shutdown button in the lobby screen. This screen only comes up when the "correct_shutdown" flag is set to False before the app starts.

![image](https://github.com/YetiTool/easycut-smartbench/assets/126763092/91a7d0d3-8801-4553-9041-41660b719191)

2023-10-17 16:39 UTC, LettyYeti requested changes
- Add new screen to start_up_sequence_test, or write appropriate visual screen test for it
- Need to resize top banner (see video in slack)
- Need to find other valid places that the console is shutdown and rebooted, at the moment the config is only updated if user shuts down console from the lobby and there are many other places where it can be shut down or rebooted :)

2024-02-22 11:44 UTC, Masc999 commented
I would even go further:
have one class that does the actual sudo calls for shutdown, restart and cancel. This function sets the flag to True.
find all instances where the console is reboot or shutdown and call the implemented functions instead.

2024-02-22 11:45 UTC, Masc999 commented
> I would even go further: have one class that does the actual sudo calls for shutdown, restart and cancel. This function sets the flag to True. find all instances where the console is reboot or shutdown and call the implemented functions instead.

2024-02-22 11:48 UTC, Masc999 requested changes

2024-02-22 11:48 UTC, Masc999 commented on src/asmcnc/skavaUI/popup_info.py
> +            os.system('sudo sed -i "s/correct_shutdown=False/correct_shutdown=True/" config.txt')
have one class that does the actual sudo calls for shutdown, restart and cancel. This function sets the flag to True.
find all instances where the console is reboot or shutdown and call the implemented functions instead.

2024-02-22 11:48 UTC, Masc999 commented on src/asmcnc/apps/start_up_sequence/start_up_sequence_manager.py
> +			if not correct_shutdown:
have one class that does the actual sudo calls for shutdown, restart and cancel. This function sets the flag to True.
find all instances where the console is reboot or shutdown and call the implemented functions instead.

2024-03-04 20:54 UTC, Masc999 requested changes

2024-03-04 20:54 UTC, Masc999 commented on src/asmcnc/apps/start_up_sequence/start_up_sequence_manager.py
> +			if not correct_shutdown:
All the file handling and flag re-setting should be done in a, let's call it, ShutdownHandler. It should also have the shutdown functions from console_utils. The start_up_sequence_manager looks the correct_shutdown state up in the ShutdownHandler.

2024-03-04 20:54 UTC, Masc999 commented on src/asmcnc/production/lower_beam_qc_jig/lower_beam_qc.py
>  	def shutdown_console(self):
Why have this function in the first place? just call console_utils.shutdown() directly

2024-03-04 20:54 UTC, Masc999 commented on src/asmcnc/production/lower_beam_qc_jig/lower_beam_qc_warranty.py
>  	def shutdown_console(self):
Why have this function in the first place? just call console_utils.shutdown() directly

2024-03-04 20:54 UTC, Masc999 commented on src/asmcnc/production/lowerbeam_calibration_jig/lowerbeam_calibration_success.py
>      def shutdown_console(self):
Why have this function in the first place? just call console_utils.shutdown() directly

2024-03-04 20:54 UTC, Masc999 commented on src/asmcnc/production/z_head_qc_jig/z_head_qc_aftr_apr_21.py
>      def do_reboot(self):
Why have this function in the first place? just call console_utils.reboot() directly

2024-03-04 20:54 UTC, Masc999 commented on src/asmcnc/production/z_head_qc_jig/z_head_qc_b4_apr_21.py
>      def do_reboot(self):
Why have this function in the first place? just call console_utils.reboot() directly

2024-03-04 20:54 UTC, Masc999 commented on src/asmcnc/apps/systemTools_app/screens/screen_factory_settings.py
>      def shutdown_console(self, dt):
Why have this function in the first place? just call console_utils.shutdown() directly

2024-03-04 20:54 UTC, Masc999 commented on src/asmcnc/production/z_head_qc_jig/z_head_qc_home.py
>      def shutdown_console(self):
Why have this function in the first place? just call console_utils.shutdown() directly

2024-03-04 20:54 UTC, Masc999 commented on src/asmcnc/skavaUI/popup_info.py
>          def cancel_shutdown(*args):
Why have this function in the first place? just call console_utils directly

2024-03-04 20:54 UTC, Masc999 commented on src/asmcnc/skavaUI/popup_info.py
>          def shutdown_now(*args):
Why have this function in the first place? just call console_utils directly

2024-03-04 20:54 UTC, Masc999 commented on src/asmcnc/skavaUI/screen_rebooting.py
>      def reboot(self, dt):
Why have this function in the first place? just call console_utils directly

2024-03-13 17:31 UTC, Masc999 commented on src/asmcnc/apps/start_up_sequence/start_up_sequence_manager.py
> +			if not correct_shutdown:
Now I know again why I wrote this: start_up_sequence_manager.py is reading the file as well. It should just read the flag from console_utils like 
`if console_utils.correct_shutdown() : do_something...`
Please fix that, so the file handling is encapsulated in console_utils

2024-03-16 21:05 UTC, Masc999 commented on src/asmcnc/production/z_head_qc_jig/z_head_qc_b4_apr_21.py
>      def do_reboot(self):
please call console_utils directly

2024-03-16 21:05 UTC, Masc999 commented on src/asmcnc/production/z_head_qc_jig/z_head_qc_aftr_apr_21.py
>      def do_reboot(self):
Please call console_utils directl<

2024-03-26 15:53 UTC, merged