Engine pr
YetiTool/easycut-smartbench pull request #1286
Opened 2023-11-10 10:58 UTC by BenjiPestell

2023-11-27 10:47 UTC, LettyYeti requested changes
See doc, address clarifications & concerns prior to merge :)

2023-12-07 14:52 UTC, LettyYeti requested changes
See comment on coordinates for approval, other comment is ticketed but non-blocking

2024-03-14 11:43 UTC, BenjiPestell commented on src/asmcnc/apps/drywall_cutter_app/engine.py
> +            finish_stepdown = self.config.active_config.cutting_depths.material_thickness
finish_stepdown = total_cut_depth

2024-03-14 12:44 UTC, Masc999 reviewed
Changes look good to me.

2024-03-14 13:51 UTC, archiepeterjarvis commented on src/asmcnc/apps/drywall_cutter_app/engine.py
> +
Some Logger.Debug through here could be nice :)

2024-03-14 21:00 UTC, archiepeterjarvis commented on src/asmcnc/apps/drywall_cutter_app/test_engine.py
> +    unittest.main()
Nice to see the test coverage 👍

2024-03-20 17:31 UTC, merged