Benji/2636/probing screen
YetiTool/easycut-smartbench pull request #1563
Opened 2024-02-23 11:25 UTC by BenjiPestell

# Added probing screen (similar to homing)

[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-2636?atlOrigin=eyJpIjoiOTlhY2EzYTAyNGRhNGNiMDhlMDUyODU5N2E3MmRiZjQiLCJwIjoiaiJ9)
- [ ] Ready for review

## Checklist
- [ ] I have completed a self review
- [ ] I have updated the [spreadsheet](https://docs.google.com/spreadsheets/d/1277nPOKtBFOk_kCo870_zA460-qlw_kGnYlLPwtnadE/edit#gid=0)
- [ ] I have updated the jira ticket
- [ ] I have added the relevant labels to this PR
- [ ] I have updated documentation (if applicable)
- [ ] I have run the unit tests suite and they pass
- [ ] I have updated the [change log](https://docs.google.com/document/d/1t3s6lQuUcug1Fj8E_i2gBJNvXN0-funwBArG2hsia6k/edit)

## Description

Sort of does what it says on the tin really

## Notes

I'm using the clock instead of binding because I was unable to bind to machine state

## Dependencies for merge
- [ ] [#<pull_request_number>]

## Testing

### Visual Test
- [ ] Not applicable
- [ ] Own computer
- [ ] Console 7"
- [ ] Console 10"

### Function Test
- [ ] Not applicable
- [ ] Own computer
- [ ] Console 7"
- [ ] Console 10"

### Unit Tests
- [ ] Not applicable
- [ ] Completed

## Screenshots (if applicable)

2024-02-26 16:38 UTC, archiepeterjarvis commented on src/asmcnc/core_UI/components/buttons/probe_button.py
> +        print("Opening probing screen")
remove print statement

2024-02-26 16:38 UTC, archiepeterjarvis commented on src/asmcnc/core_UI/components/buttons/probe_button.py
> +        print("Closing probing screen")
remove print statement

2024-02-26 16:39 UTC, archiepeterjarvis commented on src/asmcnc/core_UI/components/buttons/probe_button.py
> +        print("Opening probing screen")
(I initially had these to simulate opening/closing, but I don't think it's worth polluting logs further)

2024-02-26 16:42 UTC, archiepeterjarvis commented on src/asmcnc/core_UI/components/buttons/probe_button.py
> +        self.image = Image(source="./asmcnc/skavaUI/img/z_probe.png", size = self.size, pos = self.pos, allow_stretch = True)
Change path to a relative path, I sent doc in #software-general if needed

2024-03-04 16:06 UTC, Masc999 requested changes

2024-03-04 16:06 UTC, Masc999 commented on src/asmcnc/skavaUI/screen_probing.py
> +            if self.parent_button.return_screen == 'home':
I don't like it. The probing screen should not need to know that there might be a blinking spindle button somewhere. It just turns off the spindle in router_machine.
The blinking spindle button should bind to a spindle_on BooleanProperty that is provided by router_machine and turn its blinking on or off accordingly.

2024-03-04 16:54 UTC, Masc999 approved these changes

2024-03-04 16:55 UTC, merged